"""
Request and response models used in the FastAPI routes (and in some of the implementations).
"""
import re
from typing import Callable, Iterable, Set, Literal, Annotated
from typing import List, Dict, Any, Iterator
from datetime import datetime, timezone
import logging
import uuid
import os
import time
import traceback
import asyncio

from litellm import get_supported_openai_params
from litellm.experimental_mcp_client.client import MCPClient
from starlette.websockets import WebSocket
from pydantic import BaseModel, Field, PrivateAttr, SerializeAsAny, ValidationError, model_serializer, model_validator

from .opaca_client import OpacaClient


logger = logging.getLogger(__name__)


def get_supported_models(supports_structured_output: bool = False):
    def get_env(key: str, alt: str = '') -> list[str]:
        return os.getenv(key, alt).split(";")
    hosts = get_env("LLM_HOSTS", "openai;mistral;anthropic;gemini")
    api_keys = get_env("LLM_API_KEYS", ";;;")
    models = get_env("LLM_MODELS", "gpt-4o-mini,gpt-4o,gpt-5-mini,gpt-5;mistral-medium-latest,magistral-medium-latest;claude-sonnet-4-5,claude-opus-4-1;gemini-2.5-pro,gemini-2.5-flash")
    return [
        (url, key, models.split(","))
        for url, key, models in zip(hosts, api_keys, models)
        if url == "openai" or not supports_structured_output
    ]

# VARIOUS REST REQUEST/RESPONSE CLASSES AND INTERNAL MODEL ELEMENTS

class ConnectRequest(BaseModel):
    """
    Used as payload for the `/connect` route.

    Attributes
        url: The base url to be used for every interaction with the OPACA  platform.
        user: OPACA platform user name (when using auth), or null
        pwd: OPACA platform password (when using auth), or null
    """
    url: str
    user: str | None
    pwd: str | None


class InvokeRequest(BaseModel):
    """
    Used as payload to directly invoke an OPACA action.

    Attributes
        action: the name of the action
        agent: the name of the agent
        parameters: dict of parameters
    """
    action: str
    agent: str
    parameters: Dict[str, Any]


class InvokeResponse(BaseModel):
    """
    Response for invoke route, wrapping actual result or error, primarily to make
    the latter easier accessible from the UI.

    Attributes
        success: whether the execution was successful
        result: the actual action result; only if success=true
        error: the error-message from the container; only if success=false
    """
    success: bool
    result: Any | None
    error: str | None


class RestrictedActions(BaseModel):
    """
    Used as payload/result for /admin/restrict routes. Both lists contain string-fragments.
    Rules apply to tools where action or agent name matches (ignoring case) any of those strings.

    Attributes:
        forbidden: actions are forbidden and will result in an error if the LLM tries to call them
        need_confirmation: actions will require confirmation by the user each time they are called
    """
    forbidden: List[str]
    need_confirmation: List[str]


class QueryRequest(BaseModel):
    """
    Used as the expected body argument in the `/query/{method}` endpoints

    Attributes
        user_query: The query a user has input into the SAGE ChatBot.
        streaming: whether intermediate results should be streamed via Websocket
    """
    user_query: str
    streaming: bool = False


class AgentMessage(BaseModel):
    """
    Used as the standard response model each time an LLM Agent is invoked.
    It stores individual information generated by the various agents

    Attributes:
        agent: The name of the agent
        content: The content of the message generated by the agent
        tools: List of generated tool calls
        response_metadata: Metadata associated with the response including token usage
        execution_time: Time it took to execute the response
        formatted_output: JSON output generated by the agent, if requested with response_format
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    agent: str
    content: str = ''
    tools: List['ToolCall'] = []
    response_metadata: Dict[str, Any] = {}
    execution_time: float = .0
    formatted_output: Any = None


class QueryResponse(BaseModel):
    """
    The final response that will be sent back to the frontend. Contains a list of `AgentMessages`
    that were generated during the response generation as well as final response or error.

    Attributes:
        query: The original user query that was sent to the backend.
        agent_messages: A list of agent messages that were created during the course of the response generation.
        iterations: The total number of internal iterations that were executed before returning the final response.
        execution_time: The total execution time it took for the selected method to generate an answer.
        content: The generated response that will be shown to the user.
        error: An optional output for any error messages that were generated.
    """
    query: str = ''
    agent_messages: List[AgentMessage] = []
    iterations: int = 0
    execution_time: float = .0
    content: str = ''
    error: str = ''

    def make_error_response(self, exception: Exception) -> None:
        """Convert an exception (generic or OpacaException) to a QueryResponse to be
        returned to the Chat-UI."""
        if isinstance(exception, OpacaException):
            logger.error(f'OpacaException: {exception.error_message}\nTraceback: {traceback.format_exc()}')
            self.content = exception.user_message
            self.error = exception.error_message
        else:
            logger.error(f'Exception: {exception}\nTraceback: {traceback.format_exc()}')
            self.content = 'Generation failed'
            self.error = str(exception)


class OpacaFile(BaseModel):
    """
    Represents a single uploaded PDF file.

    Attributes:
        file_id: ID assigned after upload
        content_type: MIME type of the file
        file_name: The absolute path to the file
        host_ids: IDs assigned by each host the file has been uploaded to
        suspended: Whether the file should be excluded from future requests
    """
    file_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    content_type: str
    file_name: str
    host_ids: Dict[str, str] = Field(default_factory=dict)
    suspended: bool = False


class ChatMessage(BaseModel):
    """
    Model for storing chat history messages. Represents single messages that are generated
    during the invocation of SAGE. Can be stored as a list to be given as messages
    to a model during invocation.
    Corresponds to OpenAI's 'EasyInputMessageParam' (but simpler)

    Attributes:
        role: Role for the message, one of 'system', 'assistant', 'user', 'function', 'tool', or 'developer'.
        content: The content of the message.
    """
    role: str
    content: str | List[Dict[str, Any]]


class ToolCall(BaseModel):
    id: str
    type: Literal["opaca", "mcp"]
    name: str
    args: Dict[str, Any] = {}
    result: Any | None = None

    def without_id(self):
        """representation for tool without ID field, to be passed back to LLM (ID can be confusing)"""
        return {k: v for k, v in self.model_dump().items() if k != "id"}


class InternalTool(BaseModel):
    name: str
    description: str
    params: dict[str, str]
    required_params: list[str] | None = None
    result: str
    function: Callable
    requires_code_execution: bool = False


ToolApprovalType = Literal["ask", "deny", "allow"]


class ScheduledTask(BaseModel):
    """
    An LLM Task scheduled for later execution, by sending the query to the LLM at a later time

    Attributes:
        method: the AgentMethod originally used to create this task; will be used again for re-creating it
        task_id: ID given to this task, needed for cancelling tasks
        query: the query that will be played back to the LLM on execution
        next_time: the next time this task should be executed
        interval: interval between executions (or just until the first execution if no repetitions)
        time_of_day: execution time for daily/weekly schedules, formatted as HH:MM
        weekdays: weekdays for weekly schedules, or all weekdays for daily schedules, using 0=Monday ... 6=Sunday
        repetitions: how many more times this task should be executed; -1 for infinite (should never be zero)
    """
    method: str
    task_id: int
    query: str
    next_time: str
    interval: int
    time_of_day: str | None = None
    weekdays: List[int] | None = None
    repetitions: int


class Prompt(BaseModel):
    question: str
    icon: str = None


class PromptCategory(BaseModel):
    id: str
    header: str
    icon: str | None = None
    visible: bool = True
    is_default: bool = True
    questions: List[Prompt] = []


class Chat(BaseModel):
    """
    Stores information about each chat.

    Attributes:
        chat_id: The unique ID of the chat.
        name: human-readable name of the chat (generated or assigned)
        responses: list of full query-responses incl. intermediate messages and meta-infos
        time_created: when the chat was created
        time_modified: when the chat was last used
        is_aborted: Boolean indicating whether the current interaction should be aborted.
        is_finished: Boolean indicating whether the chat has finished generating a response for its last query.
        messages: Chat history (user queries and final LLM responses), used in subsequent requests. (derived)
    """
    chat_id: str
    name: str = ''
    responses: List[QueryResponse] = []
    time_created: datetime = Field(default_factory=lambda: datetime.now(tz=timezone.utc))
    time_modified: datetime = Field(default_factory=lambda: datetime.now(tz=timezone.utc))
    is_aborted: bool = False
    is_finished: bool = True

    @property
    def messages(self) -> Iterator[ChatMessage]:
        for r in self.responses:
            yield ChatMessage(role="user", content=r.query)
            yield ChatMessage(role="assistant", content=r.content)

    def store_interaction(self, result: QueryResponse):
        self.responses.append(result)
        self.update_modified()
        self.derive_name()

    def update_modified(self) -> None:
        self.time_modified = datetime.now(tz=timezone.utc)

    def derive_name(self) -> None:
        """derive name from first interaction, if any, and if not set yet"""
        if not self.name and self.responses:
            message = self.responses[0].query or self.responses[0].content
            self.name = (f'{message[:32]}…' if len(message) > 32 else message)


SessionPrompts = Dict[str, List[PromptCategory]]


class MCPTool(BaseModel):
    name: str
    description: str
    inputSchema: Dict[str, Any]
    server_label: str
    approval: ToolApprovalType

    def get_full_name(self) -> str:
        """Get the full tool name as expected by the LLM, including the server label."""
        return f"{self.server_label}--{self.name}"

    def cast_to_openai_tool(self) -> Dict[str, Any]:
        """Cast the MCPTool into the format expected by LiteLLM's OpenAPI tool schema."""
        return {
            "type": "function",
            "name": self.get_full_name(),
            "description": self.description,
            "parameters": self.inputSchema
        }


class MCPServerParams(BaseModel):
    server_url: str
    server_label: str
    type: str | None = None
    require_approval: str


class MCPServer(BaseModel):
    params: MCPServerParams
    tools: Dict[str, MCPTool] = Field(default_factory=dict)
    

class SessionData(BaseModel):
    """
    Stores relevant information regarding the session, including messages, configuration,
    client instances, API keys, and uploaded files.

    Attributes:
        session_id: The session's internal ID.
        chats: All the chat histories associated with the session.
        config: Configuration dictionary, one sub-dict for each method.
        uploaded_files: Dictionary storing each uploaded PDF file.
        scheduled_tasks: LLM queries scheduled for later execution by Internal Tools.
        last_scheduled_task_id: Last assigned scheduled task ID, used to generate monotonic IDs.
        notifications_chats_map: Which notifications should be auto-appended to which chats.
        valid_until: Timestamp until session is active.
        mcp_servers: All added mcp server information in JSON format.
        blocked: Whether this session is currently blocked, not accepting any requests.
        prompts: Prompt Library data.
        is_notifs_aborted: Boolean indicating if all current notification generations should be aborted.
    Transient fields:
        _websocket: Can be used to send intermediate result and other messages back to the UI
        _ws_message_queue: Used to buffer messages received from the websocket
        _ws_out_cache: Used to cache outgoing WS messages if WS is disconnected, to be sent later
        _opaca_client: Client instance for OPACA, for calling agent actions.
        _llm_clients: Dictionary of LLM client instances.
        _user_api_keys: User-provided API keys for specific LLM hosts

    Note: The websocket from the session should not be used directly; instead use the send/receive
    methods. Especially the latter is necessary to ensure that messages are properly received while
    the server is using the same method for waiting for the webserver to be closed again.
    """
    session_id: str = Field(default_factory=lambda: str(uuid.uuid4()), alias='_id')
    chats: Dict[str, Chat] = Field(default_factory=dict)
    config: Dict[str, Any] = Field(default_factory=dict)
    uploaded_files: Dict[str, OpacaFile] = Field(default_factory=dict)
    scheduled_tasks: Dict[int, ScheduledTask] = Field(default_factory=dict)
    last_scheduled_task_id: int = -1
    notifications_chats_map: Dict[int, Set[str]] = Field(default_factory=dict)
    valid_until: float = -1
    mcp_servers: Dict[str, MCPServer] = Field(default_factory=dict)
    opaca_approvals: Dict[str, Dict[str, ToolApprovalType]] = Field(default_factory=dict)
    blocked: bool = False
    prompts: SessionPrompts | None = None
    is_notifs_aborted: bool = False

    _websocket: WebSocket | None = PrivateAttr(default=None)
    _ws_msg_queue: asyncio.Queue | None = PrivateAttr(default=None)
    _ws_out_cache: list[dict] | None = PrivateAttr(default_factory=list)
    _opaca_client: OpacaClient = PrivateAttr(default_factory=OpacaClient)
    _user_api_keys: Dict[str, str] = PrivateAttr(default_factory=dict)

    @model_validator(mode="after")
    def initialize_scheduled_task_id_counter(self) -> "SessionData":
        task_ids = [self.last_scheduled_task_id]
        task_ids.extend(int(task_id) for task_id in self.scheduled_tasks)
        self.last_scheduled_task_id = max(task_ids)
        return self

    def create_scheduled_task_id(self) -> int:
        self.last_scheduled_task_id += 1
        return self.last_scheduled_task_id

    @property
    def opaca_client(self) -> OpacaClient:
        return self._opaca_client

    def is_valid(self) -> bool:
        return self.valid_until > time.time()

    def get_config(self, method) -> 'MethodConfig':
        config = self.config.get(method.NAME, method.CONFIG())
        if isinstance(config, dict):  # config is deserialized from DB as dict since the exact type is not known then
            try:
                config = method.CONFIG.model_validate(config, extra='forbid')
            except ValidationError as e:
                logger.warning(f"Config does not comply with schema; resetting to default.")
                config = method.CONFIG()
        self.config[method.NAME] = config
        return self.config[method.NAME]

    def get_or_create_chat(self, chat_id: str, create_if_missing: bool = False) -> Chat:
        chat = self.chats.get(chat_id)
        if chat is None and create_if_missing:
            chat = Chat(chat_id=chat_id)
            self.chats[chat_id] = chat
        elif chat is None and not create_if_missing:
            raise KeyError(f"Chat {chat_id} not found")
        return chat

    def delete_chat(self, chat_id: str) -> bool:
        if chat_id in self.chats:
            del self.chats[chat_id]
            return True
        return False

    def set_api_key(self, model: str, api_key: str):
        self._user_api_keys[model.rsplit("/", 1)[0]] = api_key

    def get_api_key(self, model: str) -> str | None:
        return self._user_api_keys.get(model.rsplit("/", 1)[0], None)

    def has_websocket(self) -> bool:
        return self._websocket is not None

    async def websocket_send_pending(self):
        for msg in self._ws_out_cache:
            await self._websocket.send_json(msg)
        self._ws_out_cache.clear()

    async def websocket_send(self, message: BaseModel) -> bool:
        """Send object as JSON over websocket. The JSON will include the class name as "type"."""
        typed_message = {"type": message.__class__.__name__, **message.model_dump()}
        if self._websocket:
            await self._websocket.send_json(typed_message)
            return True
        else:
            self._ws_out_cache.append(typed_message)
            return False

    async def websocket_receive(self) -> dict:
        if self._websocket and self._ws_msg_queue:
            return await self._ws_msg_queue.get()
        else:
            raise Exception("Websocket not connected")

    async def get_mcp_tools(self) -> dict[str, list[MCPTool]]:
        """Returns a list of all available mcp server tools."""
        tools = {}
        for server in self.mcp_servers.values():
            tools[server.params.server_label] = list(server.tools.values())
        return tools

    async def set_mcp_tool_approval(self, server_label: str, tool_name: str, approval: ToolApprovalType):
        """Set whether a tool call should be allowed, denied, or require confirmation by the user."""
        server = self.mcp_servers.get(server_label)
        if not server:
            raise KeyError(f"MCP server with label '{server_label}' not found.")
        
        full_name = f"{server_label}--{tool_name}"
        tool = server.tools.get(full_name)
        if not tool:
            raise KeyError(f"Tool '{full_name}' not found in MCP server '{server_label}'.")
        
        tool.approval = approval

    def get_tool_approval(self, tool_name: str) -> ToolApprovalType:
        for container_approvals in self.opaca_approvals.values():
            if tool_name in container_approvals:
                return container_approvals[tool_name]
        return "allow"

    def set_tool_approval(self, container_id: str, tool_name: str, approval: ToolApprovalType):
        if container_id not in self.opaca_approvals:
            self.opaca_approvals[container_id] = {}
        self.opaca_approvals[container_id][tool_name] = approval


    async def add_mcp_server(self, params: Dict[str, Any]) -> bool:
        """Adds a new mcp server json"""

        # Check if the server_url field is existing
        if "server_url" not in params:
            raise OpacaException("The 'server_url' field is required.", "No 'server_url' provided!", 400)

        # Check if the server url is in a valid format:
        if not re.match(r'^https?://', params["server_url"]):
            raise OpacaException("The 'server_url' needs to be in a valid url-format (e.g. 'http://<address>.com/mcp')", "Malformed 'server_url'!", 400)

        # Check if a previous mcp server with the same url already exists
        if any(m.params.server_url == params["server_url"] for m in self.mcp_servers.values()):
            raise OpacaException(f"An MCP server with the given server_url '{params['server_url']}' already exists!", "Duplicate 'server_url'!", 400)

        # If no server label was given, transform the server_url into the label
        if not params.get("server_label"):
            params["server_label"] = re.sub(r'^.*//([^/]+).*$', r'\1', params["server_url"]).replace('.', '-')
            
        label = params["server_label"]

        # Check if a previous mcp server with the same label already exists (UI saves mcp servers based on label)
        if label in self.mcp_servers:
            raise OpacaException(f"An MCP server with the given server_label '{label}' already exists!", "Duplicate 'server_label'!", 400)

        # Check if the given server-url is actually an mcp server
        client = MCPClient(server_url=params["server_url"])
        client_tools = await client.list_tools()
        if not client_tools:
            raise OpacaException(f"The given server_url '{params['server_url']}' provides no mcp tools and cannot be added!", "Unreachable MCP server!", 400)

        # Disable auto-execution of MCP tools by LiteLLM: Force it to always require approval
        # Our backend manages the permission flow itself with UI integration
        params["require_approval"] = "always"

        # Extract and remove default_approval from the mcp_server dict (prevent litellm unknown parameter exception)
        default_approval = params.pop("default_approval", "ask")

        mcp_tools = {}
        for tool in client_tools:
            full_name = f"{label}--{tool.name}"
            mcp_tools[full_name] = MCPTool(
                name=tool.name,
                description=tool.description if tool.description else '',
                inputSchema=tool.inputSchema,
                server_label=label,
                approval=default_approval
            )

        self.mcp_servers[label] = MCPServer(
            params=MCPServerParams.model_validate(params),
            tools=mcp_tools
        )
        return True

    def delete_mcp_server(self, mcp_name: str) -> bool:
        """Deletes an mcp server based on its name. The UI only stores the server_label."""
        if mcp_name in self.mcp_servers:
            del self.mcp_servers[mcp_name]
            return True
        return False

    def prune_notifications_chats_map(self):
        """Remove orphaned taskIds and invalid chatIds."""
        to_delete = []

        for task_id, chat_ids in list(self.notifications_chats_map.items()):
            # Delete map entries for tasks no longer scheduled
            if task_id not in self.scheduled_tasks:
                to_delete.append(task_id)
                continue

            # Remove chat_ids that no longer exist
            if cleaned := {cid for cid in chat_ids if cid in self.chats}:
                self.notifications_chats_map[task_id] = cleaned
            else:
                to_delete.append(task_id)

        # Remove any empty / invalid entries
        for task_id in to_delete:
            del self.notifications_chats_map[task_id]


class SearchResult(BaseModel):
    """
    Result to some search query, showing in which chat and message the string was found.

    Attributes:
        chat_id: id of the chat where the string was found
        chat_name: name of the chat where the string was found
        message_id: id of the message  where the string was found
        excerpt: some "context" showing where the string was found
    """
    chat_id: str
    chat_name: str
    message_id: int
    excerpt: str


class ExecutionResult(BaseModel):
    """
    Result of Code Execution.

    Attributes:
        run_id: Short identifier used to correlate logs for one execution.
        status: One of "success" or "error" (from Pyodide), or a handful of others like "timeout"
        stdout: Captured standard output produced by the executed code.
        stderr: Captured standard error or execution diagnostics.
    """
    run_id: str
    status: str
    stdout: str | None = None
    stderr: str | None = None


# CUSTOM EXCEPTIONS

class OpacaException(Exception):
    """
    Custom Exception class that allows to return both a user-message (shown directly in the chat bubble)
    and error message (shown when clicking on the error-marker), as well as a status code.
    """

    def __init__(self, user_message: str, error_message: str = "", status_code: int = 400):
        super().__init__(user_message)
        self.user_message = user_message
        self.error_message = error_message
        self.status_code = status_code


# MCP MESSAGES

class MCPCreateMessage(BaseModel):
    content: Dict[str, Any]


class ToolApproval(BaseModel):
    tool_name: str
    approval: ToolApprovalType


# MESSAGES SENT OR RECEIVED VIA WEBSOCKET

class TextChunkMessage(BaseModel):
    id: str
    agent: str
    chunk: str
    is_output: bool
    chat_id: str


class ReloadChatsMessage(BaseModel):
    pass


class ResetTextMessage(BaseModel):
    chat_id: str


class ToolCallMessage(BaseModel):
    agent: str
    id: str
    name: str
    args: Dict[str, Any] = {}
    chat_id: str


class ToolResultMessage(BaseModel):
    id: str
    result: Any | None
    chat_id: str


class StatusMessage(BaseModel):
    agent: str
    status: str
    chat_id: str


class MetricsMessage(BaseModel):
    agent: str
    metrics: dict
    execution_time: float
    chat_id: str


class PushAdvert(BaseModel):
    """Announcement for incoming PushMessage/Notification"""
    task_id: int
    query: str


class PushMessage(QueryResponse):
    """
    Basically just a QueryResponse, but sent via websocket at the end of "execute-later" task.

    Attributes:
        task_id: The scheduled task the PushMessage belongs to
    """
    model_config = {"extra": "ignore"}
    task_id: int


class ConfirmActionNotification(BaseModel):
    tool: str
    params: dict


class ConfirmActionResponse(BaseModel):
    allowed: bool


class ContainerLoginNotification(BaseModel):
    """
    This is a helper class to store information regarding the initiated container login.

    Attributes:
        message: An optional message to send to the frontend
        tool_name: The name of the tool that requires further credentials
        retry: Whether the login attempt has already been tried
    """
    container_name: str = ''
    tool_name: str = ''
    retry: bool = False


class ContainerLoginResponse(BaseModel):
    """
    Response to ContainerLoginNotification

    Attributes:
        username: username to use for container login
        password: password to use for container login
        timeout: automatically logout after this many seconds
    """
    username: str
    password: str
    timeout: int


class MissingApiKeyNotification(BaseModel):
    """
    Notify about missing or invalid api keys for a specific model

    Attributes:
        is_invalid: True - The api key is invalid, False - The api key is missing
        model: The model for which the api key is missing or invalid
    """
    is_invalid: bool
    model: str


class MissingApiKeyResponse(BaseModel):
    api_key: str


# METHOD CONFIGURATION

class MethodConfig(BaseModel):
    """
    Base model class that all method config classes should inherit from.
    Provides some static helper functions for easier field definitions.
    """

    @staticmethod
    def string(default: str, options: Iterable[str] = None, allow_free_input: bool = True, title: str = None, description: str = None, regex: str = None) -> Any:
        options = list(options)
        pattern = regex or (None if allow_free_input else re.compile('|'.join(options)))
        return Field(default=default, json_schema_extra={'options': options, 'allow_free_input': allow_free_input}, title=title, description=description, pattern=pattern)

    @staticmethod
    def integer(default: int, min: int, max: int, step: int, title: str = None, description: str = None) -> Any:
        return Field(default=default, ge=min, le=max, multiple_of=step, title=title, description=description)

    @staticmethod
    def number(default: float, min: float, max: float, step: float, title: str = None, description: str = None) -> Any:
        return Field(default=default, title=title, description=description, ge=min, le=max, multiple_of=step)

    @staticmethod
    def boolean(default: bool = False, title: str = None, description: str = None) -> Any:
        return Field(default=default, title=title, description=description,)

    @staticmethod
    def llm_field(title: str = None, description: str = None, supports_structured_output: bool = False) -> Any:
        models = [f"{url}/{model}" for url, _, models in get_supported_models(supports_structured_output) for model in models]
        regex = r"(?P<host>.+)/(?P<model>[\w-]+)" # the named groups are just for a better error message
        return MethodConfig.string(default=models[0], options=models, allow_free_input=True, title=title, description=description, regex=regex)

    @staticmethod
    def temperature_field(default: float = 0, min: float = 0, max: float = 2, step: float = 0.1) -> Any:
        return MethodConfig.number(default=default, min=min, max=max, step=step, title='Temperature', description='Temperature for the models')

    @staticmethod
    def max_rounds_field(default: int = 5, min: int = 1, max: int = 10, step: int = 1) -> Any:
        return MethodConfig.integer(default=default, min=min, max=max, step=step, title='Max Rounds', description='Maximum number of retries')

    @staticmethod
    def nested(model_cls: type[BaseModel], title: str = None, description: str = None) -> Any:
        return Field(default_factory=model_cls, title=title, description=description)

    @staticmethod
    def llm_role(title: str, description: str) -> Any:
        return Field(default_factory=LLMConfig, title=title, description=description)


class LLMParameters(BaseModel):
    """
    List of possible parameters for the LLM. Available parameters depend on the model.
    """
    temperature: float = MethodConfig.number(default=0, min=0, max=2, step=0.1, title="Temperature", description="Randomness of model response. Higher values will make the output more random while lower values are more deterministic")
    reasoning_effort: str = MethodConfig.string(default="low", options=["low", "medium", "high"], title="Reasoning Effort", description="How much reasoning should be applied to the model's output")
    top_p: float = MethodConfig.number(default=1, min=0, max=1, step=0.01, title="Top P", description="Alternative to temperature. Uses nucleus sampling where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the top 10% of tokens are considered")
    frequency_penalty: float = MethodConfig.number(default=0, min=-2, max=2, step=0.1, title="Frequency Penalty", description="Penalty applied to repeated tokens based on their frequency in the prompt")
    presence_penalty: float = MethodConfig.number(default=0, min=-2, max=2, step=0.1, title="Presence Penalty", description="Penalty applied to repeated tokens based on their presence in the prompt")


class LLMConfig(BaseModel):
    """
    Saves a single model and its parameter configuration. Checks during serialization what parameters are supported by the LLM.
    """
    model: Annotated[str, MethodConfig.llm_field("model", "LLM to use for this agent")]
    parameters: LLMParameters = MethodConfig.nested(LLMParameters, title="LLM Parameters", description="Parameters for the LLM")

    @model_serializer(mode="wrap")
    def filter_unsupported_params_for_serialization(self, serializer):
        """Filter out unsupported parameters from the serialized config."""
        data = serializer(self)
        data["parameters"] = self._filter_supported(data["parameters"])
        return data

    @model_validator(mode="after")
    def filter_unsupported_params_for_validation(self):
        """Filter out unsupported parameters when validated."""
        # Rebuild LLMConfig with only supported fields
        filtered = self._filter_supported(self.parameters.model_dump())
        self.parameters = LLMParameters(**filtered)
        return self
    
    def _filter_supported(self, params: dict) -> dict:
        """Remove unsupported parameters from config schema."""
        supported = get_supported_openai_params(self.model)
        filtered = {k: v for k, v in params.items() if k in supported}

        # Special handling for reasoning models not supporting temperature settings
        if any(i in self.model for i in ["gpt-5", "claude-opus", "claude-sonnet"]):
            filtered.pop("temperature", None)

        return filtered



class ConfigPayload(BaseModel):
    """
    Stores the actual values of a given configuration and the schema that is defined in `ConfigParameter`.

    Attributes
        value: Should be a JSON storing the actual values of parameters in the format `{"key": value}`
        config_schema: A JSON holding the configuration schema definition (same keys as in `value`)
    """
    config_values: SerializeAsAny[MethodConfig]
    config_schema: Dict[str, Any]
